### ISSUE TITLE
Crashes whenever I hold the crystals

### ISSUE THREAD

**Issue by EvaPlaysGameZ** [Darsenia/untouched_nature#2] opened 2023-02-17 03:51 UTC
Whenever I try and place down the crystals ( the 3d model ones ) it crashes and gives me the ticking player error. Here's my crash log if you need it ( yes I am using other mods so if there's any other incompatibility I would love to know so I can remove those mods )
[crash-2023-02-16_22.48.39-server.txt](https://github.com/Darsenia/untouched_nature/files/10763013/crash-2023-02-16_22.48.39-server.txt)

**Comment by Darsenia** [comment] 2023-02-20 18:33
Hi, I checked again all the 3d crystals (naturally spawning and those ones, that spawn fairy moss) and I couldn't reproduce this issue unless the Railcraft is installed. Railcraft for some reason grabs some basic minecraft actions and perform them (like getting properties from blocks in inventory etc) ,and it doesn't work with missing ones (forge+minecraft don't mind them).Without Railcarft everything is fine.
I can fix this issue, and post a mod patch, but it will take some time. I'm not quiet sure how many similar things could be found in this giant mod, cause they never had been an issue.
Thank you for the feedback!

**Comment by EvaPlaysGameZ** [comment] 2023-02-20 18:41
Thank you for the response and a fix will be helpful ( I'll remove
Railcraft from the modpack for now until that big is fixed )

**Comment by Darsenia** [comment] 2023-02-26 16:48
Hi, I've finally uploaded the patch, it will be available after the CurseForge approval.
There were in fact >500 blocks with rotation that Railcraft didn't understand.This issue also happened with some other different mods for years, as far as I see, and never had been fixed by Railcraft team, god knows why.
Enjoy the game! =)

**Closed as completed** 2023-03-02 21:05 UTC
Labels: good first issue
